name: 'authentik Setup'
description: 'Sets up an authentik test environment'
inputs:
  version:
    description: 'stable/beta or any other version tag'
    required: false
    default: "stable"
  sentry_env:
    description: 'Sentry environment to send traces to.'
    required: false
    default: "github-actions"
  wait:
    description: 'If the action should wait for authentik to be available'
    required: false
    default: "true"
  wait_command:
    description: 'Command to check if authentik is running and configured'
    required: false
    default: |
        while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:9000/api/v3/root/config/)" != "200" ]]; do sleep 5; done
  blueprints_path:
    description: 'Optional path to a folder containing blueprints, which are mounted into the authentik containers.'
    required: false
    default: ""

outputs:
  admin_token:
    description: "API token for akadmin User"
    value: ${{ steps.credentials.outputs.admin_token }}
  admin_password:
    description: "Password for akadmin User"
    value: ${{ steps.credentials.outputs.admin_password }}
  http_url:
    description: "Base URL to access authentik at"
    value: http://localhost:9000
  https_url:
    description: "Base URL to access authentik at (HTTPS)"
    value: https://localhost:9443
  server_container_id:
    description: id of the server container
    value: ${{ steps.run.outputs.server_container }}
  worker_container_id:
    description: id of the worker container
    value: ${{ steps.run.outputs.worker_container }}

runs:
  using: "composite"
  steps:
    - name: Generate temp dir
      shell: bash
      id: setup
      run: |
        set -xeuo pipefail
        temp_dir="${RUNNER_TEMP}/${GITHUB_ACTION}"
        mkdir -p ${temp_dir}

        echo "temp_dir=${temp_dir}" >> $GITHUB_OUTPUT

    - name: Prepare common variables
      shell: bash
      run: |
        pg_pass=$(openssl rand -base64 32)
        secret_key=$(openssl rand -base64 40)

        echo "::add-mask::${pg_pass}"
        echo "::add-mask::${secret_key}"

        echo "PG_PASS=${pg_pass}" >> "${{ steps.setup.outputs.dir }}/.env"
        echo "AUTHENTIK_SECRET_KEY=${secret_key}" >> "${{ steps.setup.outputs.dir }}/.env"
        echo "AUTHENTIK_ERROR_REPORTING__ENABLED=true" >> "${{ steps.setup.outputs.dir }}/.env"
        echo "AUTHENTIK_ERROR_REPORTING__ENVIRONMENT=${{ inputs.sentry_env }}" >> "${{ steps.setup.outputs.dir }}/.env"
        echo "AUTHENTIK_DISABLE_UPDATE_CHECK=true" >> "${{ steps.setup.outputs.dir }}/.env"
        echo "AUTHENTIK_DISABLE_STARTUP_ANALYTICS=true" >> "${{ steps.setup.outputs.dir }}/.env"

    - name: Generate credentials
      shell: bash
      id: credentials
      run: |
        AUTHENTIK_BOOTSTRAP_TOKEN=$(openssl rand -base64 32)
        echo "::add-mask::${AUTHENTIK_BOOTSTRAP_TOKEN}"
        echo "AUTHENTIK_BOOTSTRAP_TOKEN=${AUTHENTIK_BOOTSTRAP_TOKEN}" >> "${{ steps.setup.outputs.dir }}/.env"
        echo "admin_token=${AUTHENTIK_BOOTSTRAP_TOKEN}" >> $GITHUB_OUTPUT

        AUTHENTIK_BOOTSTRAP_PASSWORD=$(openssl rand -base64 32)
        echo "::add-mask::${AUTHENTIK_BOOTSTRAP_PASSWORD}"
        echo "AUTHENTIK_BOOTSTRAP_PASSWORD=${AUTHENTIK_BOOTSTRAP_PASSWORD}" >> "${{ steps.setup.outputs.dir }}/.env"
        echo "admin_password=${AUTHENTIK_BOOTSTRAP_PASSWORD}" >> $GITHUB_OUTPUT

    - name: Configure
      shell: bash
      run: |
        if [ "${{ inputs.version }}" = "beta" ]; then
          echo "AUTHENTIK_IMAGE=ghcr.io/goauthentik/dev-server" >> "${{ steps.setup.outputs.dir }}/.env"
          echo "AUTHENTIK_TAG=gh-next" >> "${{ steps.setup.outputs.dir }}/.env"
          echo "AUTHENTIK_OUTPOSTS__DOCKER_IMAGE_BASE=ghcr.io/goauthentik/dev-%(type)s:gh-%(build_hash)s" >> "${{ steps.setup.outputs.dir }}/.env"
        elif [ "${{ inputs.version }}" != "stable" ]; then
          echo "AUTHENTIK_TAG=${{ inputs.version }}" >> "${{ steps.setup.outputs.dir }}/.env"
        fi
        wget https://goauthentik.io/docker-compose.yml -o "${{ steps.setup.outputs.dir }}/docker-compose.yml"

    - name: Add override
      shell: bash
      if: ${{ inputs.blueprints_path != '' }}
      env:
        BLUEPRINTS_PATH: ${{ inputs.blueprints_path }}
      run: |
        cat <<EOT >> "${{ steps.setup.outputs.dir }}/docker-compose.override.yaml"
        services:
          server:
              volumes:
                  - ${GITHUB_WORKSPACE}/${BLUEPRINTS_PATH}:/blueprints/action-setup-authentik
        EOT

    - name: Run
      shell: bash
      id: run
      run: |
        export COMPOSE_PROJECT_NAME=authentik
        docker compose -f "${{ steps.setup.outputs.dir }}/docker-compose.yml" pull -q
        docker compose -f "${{ steps.setup.outputs.dir }}/docker-compose.yml" up -d

        server_container=$(docker ps -f label=com.docker.compose.project=authentik -f label=com.docker.compose.service=server --format "{{.ID}}")
        worker_container=$(docker ps -f label=com.docker.compose.project=authentik -f label=com.docker.compose.service=worker --format "{{.ID}}")
        echo "server_container=${server_container}" >> $GITHUB_OUTPUT
        echo "worker_container=${worker_container}" >> $GITHUB_OUTPUT

        if [ "${{ inputs.wait }}" = "true" ]; then
          timeout 600 bash -c "${{ inputs.wait_command }}" || false
        fi
        docker compose -f "${{ steps.setup.outputs.dir }}/docker-compose.yml" logs
