name: 'authentik Setup'
description: 'Sets up an authentik test environment'
inputs:
  version:
    description: 'stable/beta or any other version tag'
    required: false
    default: "stable"
  sentry_env:
    description: 'Sentry environment to send traces to.'
    required: false
    default: "github-actions"
  wait:
    description: 'If the action should wait for authentik to be available'
    required: false
    default: "true"
  wait_url:
    description: 'URL to check if authentik is running and configured'
    required: false
    default: http://localhost:9000/api/v3/root/config/
  blueprints_path:
    description: 'Optional path to a folder containing blueprints, which are mounted into the authentik containers.'
    required: false
    default: ""

outputs:
  admin_token:
    description: "API token for akadmin User"
    value: ${{ steps.prepare.outputs.admin_token }}
  admin_password:
    description: "Password for akadmin User"
    value: ${{ steps.prepare.outputs.admin_password }}
  http_url:
    description: "Base URL to access authentik at"
    value: http://localhost:9000
  https_url:
    description: "Base URL to access authentik at (HTTPS)"
    value: https://localhost:9443
  server_container_id:
    description: id of the server container
    value: ${{ steps.run.outputs.server_container }}
  worker_container_id:
    description: id of the worker container
    value: ${{ steps.run.outputs.worker_container }}

runs:
  using: "composite"
  steps:
    - name: Prepare
      shell: bash
      id: prepare
      env:
        INPUT_SENTRY_ENV: ${{ inputs.sentry_env }}
      run: |
        ${GITHUB_ACTION_PATH}/prepare.sh

    - name: Configure
      shell: bash
      env:
        INPUT_VERSION: ${{ inputs.version }}
      run: |
        ${GITHUB_ACTION_PATH}/configure.sh

    - name: Add blueprints override
      shell: bash
      if: ${{ inputs.blueprints_path != '' }}
      env:
        INPUT_BLUEPRINTS_PATH: ${{ inputs.blueprints_path }}
      run: |
        ${GITHUB_ACTION_PATH}/override_blueprints.sh

    - name: Run
      shell: bash
      id: run
      run: |
        ${GITHUB_ACTION_PATH}/start.sh

    - name: Apply blueprints
      shell: bash
      if: ${{ inputs.blueprints_path != '' }}
      run: |
        ${GITHUB_ACTION_PATH}/apply_blueprints.sh

    - name: Wait
      shell: bash
      if: ${{ inputs.wait }}
      env:
        _AK_WAIT_URL: ${{ inputs.wait_url }}
        _AK_TOKEN: ${{ steps.prepare.outputs.admin_token }}
      run: |
        echo "Waiting for authentik to be up and running..."
        timeout 600 bash "${GITHUB_ACTION_PATH}/wait.sh" || false

    - name: Logs
      shell: bash
      if: ${{ always() }}
      run: |
        ${GITHUB_ACTION_PATH}/logs.sh
