#!/bin/bash
source ${GITHUB_ACTION_PATH}/common.sh

AUTHENTIK_BOOTSTRAP_TOKEN=$(openssl rand -base64 32)
echo "::add-mask::${AUTHENTIK_BOOTSTRAP_TOKEN}"
echo "AUTHENTIK_BOOTSTRAP_TOKEN=${AUTHENTIK_BOOTSTRAP_TOKEN}" >> "${ak_temp_dir}/.env"
echo "AUTHENTIK_BOOTSTRAP_TOKEN=${AUTHENTIK_BOOTSTRAP_TOKEN}" >> $GITHUB_ENV
echo "admin_token=${AUTHENTIK_BOOTSTRAP_TOKEN}" >> $GITHUB_OUTPUT

AUTHENTIK_BOOTSTRAP_PASSWORD=$(openssl rand -base64 32)
echo "::add-mask::${AUTHENTIK_BOOTSTRAP_PASSWORD}"
echo "AUTHENTIK_BOOTSTRAP_PASSWORD=${AUTHENTIK_BOOTSTRAP_PASSWORD}" >> "${ak_temp_dir}/.env"
echo "AUTHENTIK_BOOTSTRAP_PASSWORD=${AUTHENTIK_BOOTSTRAP_PASSWORD}" >> $GITHUB_ENV
echo "admin_password=${AUTHENTIK_BOOTSTRAP_PASSWORD}" >> $GITHUB_OUTPUT
